name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull repository and deploy
        env:
          NODE_ENV: production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} << 'EOF'
            cd ${{ vars.DEPLOY_PATH }}
            git pull origin main
            npm install
            npm run build
            rm -rf /var/www/docs.gmod-integration.com
            mv ${{ vars.DEPLOY_PATH }}/build /var/www/docs.gmod-integration.com
          EOF
